### ISSUE TITLE
attempt to call a nil value (field 'append_global_mousebindings') [awesomewm-vertical]

### ISSUE THREAD

**Issue by gilded916** [AlphaTechnolog/dotfiles-v2#13]
nice config, but for some reason it just doesn't work for me. i decided to install this config on a void linux vm and i got this error
![2022-11-28_19-19](https://user-images.githubusercontent.com/101368353/204363000-185a1b44-a0d8-48c1-96b2-eb8a948ed261.png)
sorry if i'm not providing enough info, i have no idea what i'm doing

**Comment by AlphaTechnolog** [comment]
Hello! Sorry for late reply, i was so busy with some stuff and didn't see the issue. Ok did you solved the issue? Looks like it's because you did not installed awesome from git, this config requires the git version of AwesomeWM to get working, because some of the stuff used in the config isn't available in the stable one.
