### ISSUE TITLE
The icons on the bar doesnt show correctly

### ISSUE THREAD

**Issue by GerardPolloRebozado** [AlphaTechnolog/dotfiles-v2#5]
![2022-09-28-122546_1920x1080_scrot](https://user-images.githubusercontent.com/37554513/192756342-c72a08d9-a3b7-48af-9401-0c06b879ac07.png)

**Comment by AlphaTechnolog** [comment]
ok, so i reproduced as mentioned in #4 and i think i solved several icons, as you say, the taglist was showing icons really weird (like in your screenshot), so, i refactored to get it working using .svg files instead of fonts, and it seems to be working now, can you try pulling the new changes please? just remove `~/.config/awesome` and place the new `cfg/awesome` into `~/.config/awesome`, then reload awesome and you should get the taglist icons working, should look like the attached image in this comment
![pacman-taglist](https://user-images.githubusercontent.com/54639968/192787199-1d16d026-7aef-4a36-b563-13152c2a3797.png)

**Comment by GerardPolloRebozado** [comment]
Yes now they are showing. Thanks for your help and nice theme
